"""Train Model A — condition classifier (symptom text -> 5 condition classes).

TF-IDF (1-2 grams) + LogisticRegression(class_weight="balanced").
Augments the HF free-text rows with ~500 template-rendered rows generated by
the SAME app/services/feature_bridge.payload_to_text used at serve time, so
structured-form inputs are in-distribution.

Usage (from ai-service dir):
    python training/train_condition_model.py
"""
from __future__ import annotations

import itertools
import json
import random
import sys
from pathlib import Path

import joblib
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
)
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline

SERVICE_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(SERVICE_DIR))

from app.schemas.prediction import SymptomPayload  # noqa: E402
from app.services.feature_bridge import payload_to_text  # noqa: E402
from chronic_synth import generate_chronic_rows, _sample_breed_weight  # noqa: E402

REPO_ROOT = SERVICE_DIR.parents[3]
RAW_CSV = REPO_ROOT / "data" / "raw" / "pet_health_symptoms.csv"
MODEL_DIR = SERVICE_DIR / "app" / "models"
DOCS_ML_DIR = REPO_ROOT / "docs" / "ml"

RANDOM_SEED = 42

# Structured-form combinations rendered through the runtime bridge, labeled by
# the dominant signal. Keeps serve-time text in-distribution for Model A.
AUGMENT_RECIPES: list[tuple[dict, str]] = [
    # (payload overrides, condition label)
    ({"symptoms": ["skin-irritation"], "notes": "keeps scratching and licking its skin"}, "Skin Irritations"),
    ({"symptoms": ["skin-irritation", "reduced-activity"], "notes": "red patches on belly"}, "Skin Irritations"),
    ({"symptoms": ["skin-irritation"], "notes": "hair loss and flaky skin"}, "Skin Irritations"),
    ({"vomiting_frequency": "multiple", "diarrhea_level": "moderate", "appetite_level": "reduced"}, "Digestive Issues"),
    ({"vomiting_frequency": "persistent", "appetite_level": "none", "notes": "stomach gurgling loudly"}, "Digestive Issues"),
    ({"diarrhea_level": "severe", "appetite_level": "reduced", "symptoms": ["lethargy"]}, "Digestive Issues"),
    ({"symptoms": ["lethargy"], "appetite_level": "reduced", "notes": "scooting and visible worms in stool"}, "Parasites"),
    ({"symptoms": ["lethargy", "reduced-activity"], "notes": "flea dirt in fur, itchy coat"}, "Parasites"),
    ({"symptoms": ["ear-scratching", "head-shaking"], "notes": "smelly discharge from ear"}, "Ear Infections"),
    ({"symptoms": ["ear-scratching"], "notes": "keeps tilting head and shaking it"}, "Ear Infections"),
    ({"symptoms": ["stiff-gait", "reduced-activity"], "notes": "limping on rear leg"}, "Mobility Problems"),
    ({"symptoms": ["stiff-gait"], "activity_level": "lethargic", "notes": "struggles to climb stairs"}, "Mobility Problems"),
]


def build_augmented_rows(n_target: int = 500) -> pd.DataFrame:
    rng = random.Random(RANDOM_SEED)
    species_cycle = itertools.cycle(["dog", "cat"])
    rows = []
    while len(rows) < n_target:
        overrides, label = rng.choice(AUGMENT_RECIPES)
        species = next(species_cycle)
        # obesity stresses joints -> bias Mobility Problems overweight; others ideal
        breed, weight = _sample_breed_weight(rng, species, "over" if label == "Mobility Problems" else "ideal")
        payload = SymptomPayload(
            pet_id="aug",
            species=species,
            breed=breed,
            weight_kg=weight,
            appetite_level=overrides.get("appetite_level", "normal"),
            water_intake=overrides.get("water_intake", "normal"),
            activity_level=overrides.get("activity_level", "normal"),
            urine_frequency=overrides.get("urine_frequency", "normal"),
            vomiting_frequency=overrides.get("vomiting_frequency", "none"),
            diarrhea_level=overrides.get("diarrhea_level", "none"),
            symptoms=overrides.get("symptoms", []),
            notes=overrides.get("notes", ""),
            symptom_duration_days=rng.choice([1, 2, 3, 5, 7]),
        )
        rows.append({"text": payload_to_text(payload), "condition": label})
    return pd.DataFrame(rows)


def main() -> int:
    if not RAW_CSV.exists():
        print(f"Dataset missing: {RAW_CSV}\nRun: python training/download_datasets.py")
        return 1

    df = pd.read_csv(RAW_CSV)
    text_col = "text" if "text" in df.columns else df.columns[0]
    label_col = "condition" if "condition" in df.columns else df.columns[1]
    df = df[[text_col, label_col]].dropna().rename(columns={text_col: "text", label_col: "condition"})
    print(f"Loaded {len(df)} rows; classes: {sorted(df['condition'].unique())}")

    aug = build_augmented_rows(500)
    chronic = pd.DataFrame(generate_chronic_rows(per_disease=450, seed=RANDOM_SEED))
    print(f"Chronic synthetic rows: {len(chronic)} across {chronic['condition'].nunique()} diseases")
    full = pd.concat([df, aug, chronic], ignore_index=True)
    print(f"After augmentation: {len(full)} rows, {full['condition'].nunique()} classes")

    X_train, X_test, y_train, y_test = train_test_split(
        full["text"], full["condition"], test_size=0.2, random_state=RANDOM_SEED, stratify=full["condition"]
    )

    pipeline = Pipeline(
        [
            ("tfidf", TfidfVectorizer(ngram_range=(1, 2), min_df=2, max_features=20000, lowercase=True)),
            ("clf", LogisticRegression(max_iter=1000, class_weight="balanced", random_state=RANDOM_SEED)),
        ]
    )
    pipeline.fit(X_train, y_train)

    y_pred = pipeline.predict(X_test)
    labels = sorted(full["condition"].unique())
    metrics = {
        "model": "TfidfVectorizer(1-2grams) + LogisticRegression(balanced)",
        "dataset": "karenwky/pet-health-symptoms-dataset + 500 template-augmented rows + 2700 knowledge-grounded chronic-disease rows (6 diseases)",
        "n_train": int(len(X_train)),
        "n_test": int(len(X_test)),
        "accuracy": round(float(accuracy_score(y_test, y_pred)), 4),
        "macro_f1": round(float(f1_score(y_test, y_pred, average="macro")), 4),
        "labels": labels,
        "classification_report": classification_report(y_test, y_pred, output_dict=True),
        "confusion_matrix": confusion_matrix(y_test, y_pred, labels=labels).tolist(),
    }

    MODEL_DIR.mkdir(parents=True, exist_ok=True)
    joblib.dump(pipeline, MODEL_DIR / "condition_model.joblib")
    with open(MODEL_DIR / "condition_metrics.json", "w", encoding="utf-8") as fh:
        json.dump(metrics, fh, indent=2)

    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        from sklearn.metrics import ConfusionMatrixDisplay

        DOCS_ML_DIR.mkdir(parents=True, exist_ok=True)
        fig, ax = plt.subplots(figsize=(8, 7))
        ConfusionMatrixDisplay(
            confusion_matrix(y_test, y_pred, labels=labels), display_labels=labels
        ).plot(ax=ax, xticks_rotation=30, colorbar=False)
        ax.set_title("Model A — Condition Classifier Confusion Matrix")
        fig.tight_layout()
        fig.savefig(DOCS_ML_DIR / "condition_confusion_matrix.png", dpi=150)
        print(f"Saved confusion matrix -> {DOCS_ML_DIR / 'condition_confusion_matrix.png'}")
    except Exception as ex:
        print(f"(confusion matrix plot skipped: {ex})")

    print(f"accuracy={metrics['accuracy']} macro_f1={metrics['macro_f1']}")
    print(f"Saved model -> {MODEL_DIR / 'condition_model.joblib'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
